#! /bin/sh

# notify
dunst &

# fix cursor
xsetroot -cursor_name left_ptr &

# polkit
/usr/lib/polkit-gnome/polkit-gnome-authentication-agent-1 &

# wallpaper
nitrogen --restore &

# effects
picom -f &

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         1
bspc config window_gap           1

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc rule -a Chromium desktop='^10' follow=on
